import {test,expect} from '@playwright/test'
test('at mention searches Agent and Group, preserves message text and carries the selected target to Core',async({page})=>{
 await page.goto('http://127.0.0.1:5173');await page.getByRole('button',{name:'新会话',exact:true}).click()
 await expect(page.getByRole('combobox',{name:'伙伴与团队',exact:true})).toHaveCount(0)
 const input=page.getByRole('textbox',{name:'消息',exact:true})
 await input.fill('请检查 @Cod')
 await expect(page.getByRole('group',{name:'Agent',exact:true})).toBeVisible()
 await expect(page.getByRole('option',{name:'Coder',exact:true})).toBeVisible()
 await input.press('Enter');await expect(input).toHaveValue('请检查 ')
 await expect(page.getByText('@Coder',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'取消对话对象',exact:true}).click()
 await expect(page.getByText('@Coder',{exact:true})).toHaveCount(0)
 await input.fill('@Dev')
 await expect(page.getByRole('group',{name:'Group',exact:true})).toBeVisible()
 await page.getByRole('option',{name:'Dev Team',exact:true}).click()
 await expect(input).toHaveValue('');await expect(page.getByText('@Dev Team',{exact:true})).toBeVisible()
 await input.fill('检查项目')
 const sent=page.waitForRequest(r=>r.method()==='POST'&&r.url().endsWith('/send'))
 await page.getByRole('button',{name:'发送消息',exact:true}).click()
 expect((await sent).postDataJSON()).toMatchObject({text:'检查项目',context:{agent:'Dev Team'}})
 await expect(page.getByRole('alert')).toContainText('Agent/Group 执行尚未接入')
 await expect(input).toHaveValue('检查项目')
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'收起侧栏',exact:true}).click()
 await input.fill('@');await expect(page.getByRole('group',{name:'Group',exact:true})).toBeVisible()
 await page.screenshot({path:'artifacts/browser/agent-mention-narrow.png'})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await input.press('Escape');await expect(page.getByRole('listbox',{name:'命令列表',exact:true})).toHaveCount(0)
 await input.fill('mail@example.com');await expect(page.getByRole('listbox',{name:'命令列表',exact:true})).toHaveCount(0)
})
