import { test, expect } from '@playwright/test'

test('assistant-ui renders rich conversations, tools, attachments and retry', async ({ page, context }) => {
 const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
 await context.grantPermissions(['clipboard-read', 'clipboard-write'])
 await page.setViewportSize({ width: 1440, height: 1000 })
 await page.goto('http://127.0.0.1:5173')
 const choose = async (title: string) => { await page.getByRole('button', { name: title, exact: true }).click() }
 await choose('排版 · 项目计划与对比')
 await expect(page.locator('[data-chat-engine="assistant-ui"]')).toBeVisible()
 await expect(page.getByRole('table')).toBeVisible()
 await expect(page.locator('.markdown-content input[type=checkbox]')).toHaveCount(4)
 await page.screenshot({ path: 'artifacts/aui-markdown.png', animations: 'disabled' })
 await choose('代码 · 实现与修改对比')
 await expect(page.locator('.markdown-content pre')).toHaveCount(3)
 await page.getByRole('button', { name: '复制代码' }).first().click()
 expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('function updateContext')
 await page.screenshot({ path: 'artifacts/aui-code.png', animations: 'disabled' })
 await choose('工具 · 文件、Shell 与失败')
 await page.getByRole('button',{name:'耗时未记录',exact:true}).click()
 await page.getByRole('button',{name:'3 次工具调用',exact:true}).click()
 await expect(page.locator('.tool-activity')).toHaveCount(3)
 await page.getByRole('button', { name: 'shell 失败' }).click()
 await expect(page.getByText('Exit code: 1', { exact: false })).toBeVisible()
 await page.screenshot({ path: 'artifacts/aui-tools.png', animations: 'disabled' })
 await page.getByRole('button', { name: '团队 · Coder / Reviewer / Tester', exact: true }).click()
 await page.getByRole('button',{name:'耗时未记录',exact:true}).click()

 await expect(page.locator('.team-task')).toHaveCount(3)
 await expect(page.getByRole('heading', { name: '团队结论' })).toBeVisible()
 await choose('附件 · 图片与文档')
 await expect(page.getByText('Ailya-requirements.pdf', { exact: true })).toBeVisible()
 const image = page.getByRole('img', { name: '内置布局示意图' })
 await expect(image).toBeVisible()
 expect(await image.evaluate((node: HTMLImageElement) => node.complete && node.naturalWidth > 0)).toBe(true)
 await page.screenshot({ path: 'artifacts/aui-attachments.png', animations: 'disabled' })
 await choose('异常 · 连接失败与重试')
 await expect(page.locator('.error-status')).toBeVisible()
 await page.getByRole('button', { name: '重试回复' }).click()
 await expect(page.getByRole('button', { name: '停止生成' })).toBeVisible()
 await expect(page.getByRole('button', { name: '停止生成' })).toBeHidden({ timeout: 10000 })
 await expect(page.locator('.error-status')).toHaveCount(0)
 await expect(page.getByText('回复已恢复。', { exact: true })).toBeVisible()
 await choose('中断 · 停止后继续')
 await expect(page.getByText('已停止生成')).toBeVisible()
 await page.getByRole('button', { name: '重试回复' }).click()
 await expect(page.getByRole('button', { name: '停止生成' })).toBeVisible()
 await page.getByRole('button', { name: '停止生成' }).click()
 await choose('长对话 · 多轮上下文')
 await expect(page.locator('.user-message')).toHaveCount(8)
 await expect(page.locator('.assistant-message')).toHaveCount(8)
 await page.getByRole('button', { name: '回到最新消息' }).click()
 await expect(page.getByRole('heading', { name: '已确定' })).toBeVisible()
 await page.setViewportSize({ width: 390, height: 844 })
 await page.getByRole('button', { name: '收起侧栏' }).click()
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
 await page.screenshot({ path: 'artifacts/aui-mobile.png', animations: 'disabled' })
 expect(errors).toEqual([])
})

test('existing local sessions survive demo migration and switching does not mix streams', async ({ page }) => {
 await page.addInitScript(() => {
  if (localStorage.getItem('migration-test')) return
  localStorage.setItem('migration-test', 'done')
  localStorage.setItem('ailya-prototype-v1', JSON.stringify({ state: { activeId: 'my-session', sessions: [{ id: 'my-session', title: '我的已有会话', group: '今天', context: { workspace: 'Ailya', agent: 'Ailya', model: '默认模型' }, messages: [{ id: 'original-user', role: 'user', text: '保留这条消息' }] }] }, version: 0 }))
 })
 await page.goto('http://127.0.0.1:5173')
 await expect(page.getByText('保留这条消息', { exact: true })).toBeVisible()
 await expect(page.getByRole('button', { name: '排版 · 项目计划与对比', exact: true })).toBeVisible()
 await page.getByRole('textbox', { name: '消息', exact: true }).fill('测试流式隔离')
 await page.getByRole('button', { name: '发送消息' }).click()
 await expect(page.getByRole('button', { name: '停止生成' })).toBeVisible()
 await page.getByRole('button', { name: '代码 · 实现与修改对比', exact: true }).click()
 await expect(page.getByText('测试流式隔离', { exact: true })).toHaveCount(0)
 await page.getByRole('button', { name: '我的已有会话', exact: true }).click()
 await expect(page.getByText('测试流式隔离', { exact: true })).toBeVisible()
 await page.getByRole('button', { name: '停止生成' }).click()
 await page.reload()
 await expect(page.getByText('保留这条消息', { exact: true })).toBeVisible()
 await expect(page.getByText('已停止生成', { exact: true })).toBeVisible()
})





