import {test,expect} from '@playwright/test'
test('MCP and schedule configuration persist in Core; Tavily live search; desktop and narrow layout',async({page,request})=>{
 test.setTimeout(60000)
 const name='Browser MCP '+Date.now(),task='Browser schedule '+Date.now(),created:string[]=[]
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 try{
  await page.goto('http://127.0.0.1:5173')
  await page.getByRole('button',{name:'扩展',exact:true}).click()
  await page.getByRole('button',{name:'新增 MCP',exact:true}).click()
  await page.getByLabel('名称',{exact:true}).fill(name)
  await page.getByLabel('启动命令',{exact:true}).fill('node local-mcp.js')
  await page.getByLabel('环境变量 JSON',{exact:true}).fill('{"TEST":"browser-value"}')
  await page.getByRole('button',{name:'保存',exact:true}).click()
  await expect(page.getByRole('heading',{name,exact:true})).toBeVisible()
  const rows=await (await request.get('http://127.0.0.1:5173/api/resources')).json()
  const entry=rows.find((r:{name:string})=>r.name===name);created.push(entry.id);expect(entry.env).toEqual({TEST:'browser-value'});expect(entry.enabled).toBe(false)
  await page.reload();await page.getByRole('button',{name:'Agent',exact:true}).click()
  await page.getByRole('button',{name:'新增 Agent',exact:true}).click()
  await page.getByRole('button',{name:'Tools',exact:true}).click()
  await expect(page.getByRole('option',{name,exact:true})).toBeVisible()
  await page.keyboard.press('Escape');await page.getByRole('button',{name:'取消',exact:true}).click()
  await page.getByRole('button',{name:'扩展',exact:true}).click()
  await expect(page.getByRole('heading',{name,exact:true})).toBeVisible()
  await page.getByRole('button',{name:'定时任务',exact:true}).click()
  await page.getByRole('button',{name:'新增 定时任务',exact:true}).click()
  await page.getByLabel('名称',{exact:true}).fill(task)
  await page.getByLabel('任务内容',{exact:true}).fill('Browser persistence test; disabled, do not execute')
  await page.getByRole('button',{name:'保存',exact:true}).click()
  await expect(page.getByRole('heading',{name:task,exact:true})).toBeVisible()
  const tasks=await (await request.get('http://127.0.0.1:5173/api/resources')).json();created.push(tasks.find((r:{name:string})=>r.name===task).id)
  await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'模型与连接',exact:true}).click()
  await expect(page.getByRole('button',{name:'测试搜索',exact:true})).toBeEnabled()
  await page.getByRole('button',{name:'测试搜索',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('连接成功，返回 3 条结果',{timeout:25000})
  await page.getByLabel('Tavily API Key',{exact:true}).scrollIntoViewIfNeeded()
  await page.screenshot({path:'artifacts/browser/tools-desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  await page.getByLabel('Tavily API Key',{exact:true}).scrollIntoViewIfNeeded()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'artifacts/browser/tools-narrow.png',fullPage:true})
  expect(errors).toEqual([])
 }finally{for(const id of created)expect((await request.delete('http://127.0.0.1:5173/api/resources/'+id,{data:{}})).ok()).toBe(true)}
})
