import {test,expect} from '@playwright/test'
test('real Core chat, reload persistence, provider CRUD and responsive layout',async({page,request})=>{
 test.setTimeout(90000)
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/snapshot')),page.goto('http://127.0.0.1:5173')])
 await page.getByRole('button',{name:'新会话',exact:true}).first().click()
 await expect(page.getByRole('alert')).toHaveCount(0)
 await page.getByRole('textbox',{name:'消息',exact:true}).fill('请仅回复 AILYA_BROWSER_OK，不要使用工具。')
 await expect(page.getByRole('button',{name:'发送消息',exact:true})).toBeEnabled()
 const sendRequest=page.waitForRequest(r=>r.method()==='POST'&&r.url().endsWith('/send'))
 await page.getByRole('button',{name:'发送消息',exact:true}).click()
 const sentSessionId=(await sendRequest).url().split('/').at(-2)!
 await expect(page.locator('.assistant-message').last()).toContainText('AILYA_BROWSER_OK',{timeout:60000})
 await expect(page.getByRole('button',{name:'停止生成'})).toHaveCount(0,{timeout:60000})
 await page.reload()
 await expect(page.locator('.assistant-message').last()).toContainText('AILYA_BROWSER_OK')
 await page.screenshot({path:'artifacts/browser/desktop.png',fullPage:true})
 await page.getByRole('button',{name:'设置',exact:true}).click()
 await page.getByRole('button',{name:'模型与连接',exact:true}).click()
 await page.getByRole('button',{name:'添加厂商',exact:true}).click()
 await page.getByLabel('厂商名称').fill('Browser CRUD')
 await page.getByLabel('Base URL').fill('http://127.0.0.1:9999')
 await page.getByLabel('API Key',{exact:true}).fill('browser-test-secret')
 await page.getByLabel('模型 ID',{exact:true}).fill('test-model')
 await page.getByRole('button',{name:'添加',exact:true}).click()
 await page.getByRole('button',{name:'保存厂商'}).click()
 await expect(page.getByRole('button',{name:'编辑 Browser CRUD'})).toBeVisible()
 await page.getByRole('button',{name:'编辑 Browser CRUD'}).click()
 await expect(page.getByLabel('API Key',{exact:true})).toHaveValue('')
 await page.getByRole('button',{name:'取消',exact:true}).click()
 expect(await page.evaluate(()=>JSON.stringify(localStorage))).not.toContain('browser-test-secret')
 await page.getByRole('button',{name:'删除 Browser CRUD'}).click()
 await page.getByRole('button',{name:'删除',exact:true}).click()
 await expect(page.getByRole('button',{name:'编辑 Browser CRUD'})).toHaveCount(0)
 await page.getByRole('button',{name:'本地 Core',exact:true}).click()
 await expect(page.getByRole('dialog')).toContainText('已连接')
 await page.getByRole('button',{name:'关闭',exact:true}).click()
 await page.setViewportSize({width:390,height:844})
 await page.getByRole('button',{name:'收起侧栏',exact:true}).click()
 await expect(page.locator('.assistant-message').last()).toContainText('AILYA_BROWSER_OK')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:'artifacts/browser/narrow.png',fullPage:true})
 expect(errors).toEqual([])
 expect((await request.delete('http://127.0.0.1:5173/api/sessions/'+sentSessionId,{data:{}})).ok()).toBe(true)
})



test('real file tool reaches existing diff UI, then stop survives reload',async({page,request})=>{
 test.setTimeout(90000)
 const {mkdtempSync,readFileSync,rmSync}=await import('node:fs')
 const {tmpdir}=await import('node:os');const {join}=await import('node:path')
 const root=mkdtempSync(join(tmpdir(),'ailya-browser-tool-')),id=crypto.randomUUID()
 try{
  const sent=await request.post(`http://127.0.0.1:5173/api/sessions/${id}/send`,{data:{requestId:crypto.randomUUID(),text:'Use write exactly once to create proof.txt containing exactly browser proof, then reply DONE.',context:{workspace:root,agent:'Ailya',model:'默认模型',permission:'full'}}})
  expect(sent.status()).toBe(202)
  await page.goto('http://127.0.0.1:5173')
  await page.evaluate(id=>sessionStorage.setItem('ailya-active-session',id),id);await page.reload()
  await expect(page.getByRole('region',{name:'文件修改'})).toContainText('proof.txt',{timeout:60000})
  await expect(page.getByRole('button',{name:'停止生成'})).toHaveCount(0,{timeout:60000})
  expect(readFileSync(join(root,'proof.txt'),'utf8')).toBe('browser proof')
  await page.getByRole('button',{name:'查看差异 '+join(root,'proof.txt')}).click()
  await expect(page.getByRole('dialog')).toContainText('browser proof')
  await page.screenshot({path:'artifacts/browser/file-diff.png',fullPage:true})
  await page.getByRole('button',{name:'关闭',exact:true}).click()
  await page.getByRole('textbox',{name:'消息',exact:true}).fill('请从 1 到 10000 逐个列出数字，不要使用工具。')
  const sendRequest=page.waitForRequest(r=>r.method()==='POST'&&r.url().endsWith('/send'))
 await page.getByRole('button',{name:'发送消息',exact:true}).click()
 await sendRequest
  await page.getByRole('button',{name:'停止生成'}).click()
  await expect(page.locator('.assistant-message').last()).toContainText('已停止生成',{timeout:15000})
  await page.reload()
  await expect(page.locator('.assistant-message').last()).toContainText('已停止生成')
 }finally{
  await request.post(`http://127.0.0.1:5173/api/sessions/${id}/stop`,{data:{}})
  await expect.poll(async()=>{const snapshot=await (await request.get('http://127.0.0.1:5173/api/snapshot')).json();return snapshot.sessions.find((s:{id:string})=>s.id===id)?.messages.some((m:{executing?:boolean})=>m.executing)??false}).toBe(false)
  await request.delete(`http://127.0.0.1:5173/api/sessions/${id}`,{data:{}})
  rmSync(root,{recursive:true,force:true})
 }
})


