import { useState } from 'react'
import { FileCode, ChevronDown } from 'lucide-react'
import { Button } from './ui/button'
import { Dialog, DialogContent, DialogTitle } from './ui/dialog'
export type FileChange={path:string;added:number;deleted:number;kind:'modified'|'added'|'deleted'|'renamed';oldPath?:string;binary?:boolean;truncated?:boolean;oldStart?:number;newStart?:number;diff?:string[]}
export function FileChanges({files}:{files:FileChange[]}){
 const [open,setOpen]=useState(false)
 const [selected,setSelected]=useState<FileChange|null>(null)

 return <><section aria-label="文件修改" className="my-4 overflow-hidden rounded-lg border bg-popover"><div className="flex items-center justify-between border-b px-3 py-2 text-xs"><span>{files.length} 个文件已修改</span><span className="flex gap-3 tabular-nums"><span className="text-green-700">+{files.reduce((n,f)=>n+f.added,0)}</span><span className="text-rose-700">−{files.reduce((n,f)=>n+f.deleted,0)}</span></span></div>{(open?files:files.slice(0,2)).map(f=><button type="button" key={f.path} aria-label={`查看差异 ${f.path}`} title="查看文件差异" onClick={()=>setSelected(f)} className="flex w-full items-start gap-2 border-b px-3 py-3 text-left text-xs transition-colors last:border-0 hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring"><FileCode className="size-4 shrink-0 text-muted-foreground"/><span className="min-w-0 flex-1 break-all font-mono">{f.path}</span>{f.binary?<span className="text-muted-foreground">二进制</span>:<><span className="shrink-0 text-green-700">+{f.added}</span><span className="shrink-0 text-rose-700">−{f.deleted}</span></>}</button>)}{files.length>2&&<Button variant="ghost" className="h-8 w-full rounded-none text-xs" aria-expanded={open} onClick={()=>setOpen(!open)}><ChevronDown className={open?'size-3 rotate-180':'size-3'}/>{open?'收起':`展开其余 ${files.length-2} 个文件`}</Button>}</section>
 <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent aria-describedby={undefined} className="flex max-h-[85dvh] w-[calc(100%-2rem)] max-w-5xl flex-col gap-0 overflow-hidden p-0"><div className="border-b p-4 pr-12"><DialogTitle className="break-all font-mono text-sm leading-6">{selected?.path}</DialogTitle>{selected?.oldPath&&<p className="mt-2 break-all font-mono text-xs text-muted-foreground">原路径：{selected.oldPath}</p>}<div className="mt-2 flex gap-3 text-xs tabular-nums">{!selected?.binary&&<><span className="text-green-700">+{selected?.added}</span><span className="text-rose-700">−{selected?.deleted}</span></>}</div></div><div className="overflow-auto" tabIndex={0} aria-label="文件差异">{selected?.diff?.length?<div className="min-w-max py-3 font-mono text-xs leading-6">{(()=>{let oldLine=(selected.oldStart??1)-1,newLine=(selected.newStart??1)-1;return selected.diff.map((line,i)=>{const hunk=line.match(/^@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)? @@/);if(hunk){oldLine=Number(hunk[1])-1;newLine=Number(hunk[2])-1;return <div key={i} className="bg-muted px-4 text-muted-foreground"><code>{line}</code></div>}if(line.startsWith('\\ No newline'))return <div key={i} className="px-4 text-muted-foreground">{line}</div>;const add=line.startsWith('+'),del=line.startsWith('-');if(!add)oldLine++;if(!del)newLine++;return <div key={i} className={`flex pr-5 ${add?'bg-green-50 text-green-900':del?'bg-rose-50 text-rose-900':''}`}><span className="w-10 shrink-0 select-none text-right text-muted-foreground">{add?'':oldLine}</span><span className="mr-3 w-10 shrink-0 select-none text-right text-muted-foreground">{del?'':newLine}</span><span className="w-5 shrink-0 select-none">{add?'+':del?'−':' '}</span><code className="whitespace-pre">{line.slice(1)}</code></div>})})()}</div>:<p className="p-6 text-sm text-muted-foreground">{selected?.binary?'二进制文件，无法显示文本差异':'暂无差异内容'}</p>}{selected?.truncated&&<p className="border-t p-3 text-xs text-muted-foreground">差异内容已截断</p>}</div></DialogContent></Dialog>
 </>
}




