import { useState } from 'react'
import { usePlugins,type Plugin } from '../plugins'
import { Button } from './ui/button'
import { Input } from './ui/input'
import { Dialog,DialogContent,DialogTitle,DialogFooter } from './ui/dialog'
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from './ui/select'
import { AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogFooter,AlertDialogCancel } from './ui/alert-dialog'
export function PluginLibrary(){
 const {items,save,remove}=usePlugins();const [form,setForm]=useState<Plugin|null>(null);const [deleting,setDeleting]=useState<Plugin|null>(null);const [query,setQuery]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('')
 const rows=items.filter(p=>p.source.toLowerCase().includes(query.toLowerCase()))
 return <><div className="mb-6 flex flex-wrap justify-between gap-3"><Input className="max-w-xs" aria-label="搜索插件" placeholder="搜索" value={query} onChange={e=>setQuery(e.target.value)}/><Button size="sm" onClick={()=>{setError('');setForm({id:crypto.randomUUID(),kind:'npm',source:'',enabled:true})}}>安装插件</Button></div>
 {notice&&<p role="status" className="mb-4 text-sm">{notice}</p>}
 <div className="grid gap-4 sm:grid-cols-2">{rows.map(p=><article key={p.id} className="min-w-0 rounded-lg border bg-popover p-4"><h2 className="mb-3 break-all text-sm font-medium">{p.source}</h2><div className="mb-4 flex gap-3 text-xs text-muted-foreground"><span>{p.kind}</span><span>{p.enabled?'待加载':'已停用'}</span></div><div className="flex flex-wrap gap-1 border-t pt-3"><Button size="sm" variant="ghost" onClick={()=>save({...p,enabled:!p.enabled})}>{p.enabled?'停用':'启用'}</Button><Button size="sm" variant="ghost" onClick={()=>setNotice('本地 Core 未连接，无法更新插件。')}>更新</Button><Button size="sm" variant="ghost" onClick={()=>setNotice('本地 Core 未连接，无法重新加载插件。')}>重新加载</Button><Button variant="ghost" size="sm" onClick={()=>{setError('');setForm({...p})}}>编辑</Button><Button variant="ghost" size="sm" onClick={()=>setDeleting(p)}>卸载</Button></div></article>)}</div>{!rows.length&&<div className="py-12 text-center text-sm text-muted-foreground">{query?'没有匹配项':'暂无插件'}</div>}
 <Dialog open={!!form} onOpenChange={v=>{if(!v)setForm(null)}}><DialogContent aria-describedby={undefined}><DialogTitle>{items.some(p=>p.id===form?.id)?'编辑插件':'安装插件'}</DialogTitle>{form&&<form id="plugin-form" className="space-y-4" onSubmit={e=>{e.preventDefault();const source=form.source.trim();if(!source){setError('请输入插件来源');return}if(items.some(p=>p.id!==form.id&&p.source===source)){setError('该插件已存在');return}save({...form,source});setForm(null);setNotice('配置已保存，连接本地 Core 后安装。')}}><Select value={form.kind} onValueChange={kind=>setForm({...form,kind,source:''})}><SelectTrigger aria-label="来源类型"><SelectValue/></SelectTrigger><SelectContent>{['npm','Git','本地路径'].map(value=><SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select><label className="block space-y-2 text-sm">插件来源<Input value={form.source} placeholder={form.kind==='npm'?'npm:@scope/package@version':form.kind==='Git'?'git:github.com/user/repo@tag':'本地文件或目录路径'} onChange={e=>setForm({...form,source:e.target.value})}/></label>{error&&<p role="alert" className="text-sm">{error}</p>}</form>}<DialogFooter><Button variant="outline" onClick={()=>setForm(null)}>取消</Button><Button type="submit" form="plugin-form">保存</Button></DialogFooter></DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={v=>{if(!v)setDeleting(null)}}><AlertDialogContent aria-describedby={undefined}><AlertDialogTitle>移除插件配置？</AlertDialogTitle><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><Button onClick={()=>{if(deleting)remove(deleting.id);setDeleting(null)}}>移除</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>
}
