import { PluginLibrary } from './PluginLibrary'
import { useState,useEffect } from 'react'
import { Plus, Pencil, Trash2, Plug, BookOpen, Clock } from 'lucide-react'
import { useResources,createResource,resourceLabel,scheduleLabel,type Resource,type ResourceKind } from '../resources'
import { Button } from './ui/button'
import { Input } from './ui/input'
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from './ui/alert-dialog'
export function ResourceLibrary({mode,edit}:{mode:'extensions'|'tasks';edit:(entry:Resource)=>void}){
 const {items,remove,toggle,load,error}=useResources();const [tab,setTab]=useState<ResourceKind|'plugin'>('mcp');const [query,setQuery]=useState('');const [deleting,setDeleting]=useState<Resource|null>(null)
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),5000);return()=>clearInterval(timer)},[load])
 const kind=mode==='tasks'?'task':tab==='plugin'?'mcp':tab;const Icon=kind==='mcp'?Plug:kind==='skill'?BookOpen:Clock
 const rows=items.filter(x=>x.kind===kind&&x.name.toLowerCase().includes(query.toLowerCase()))
 return <div className="min-h-0 flex-1 overflow-auto p-5 md:p-8"><div className="mx-auto max-w-5xl"><div className="mb-6 flex items-center justify-between gap-3"><h1 className="text-xl font-medium">{mode==='tasks'?'定时任务':'扩展'}</h1>{!(mode==='extensions'&&tab==='plugin')&&<Button size="sm" onClick={()=>edit(createResource(kind))}><Plus/>新增 {resourceLabel[kind]}</Button>}</div>{mode==='extensions'&&<div className="mb-5 flex gap-2" role="tablist" aria-label="扩展类型">{(['plugin','mcp','skill'] as const).map(t=><Button role="tab" aria-selected={tab===t} key={t} variant={tab===t?'secondary':'ghost'} onClick={()=>{setTab(t);setQuery('')}}>{t==='plugin'?'插件':t==='mcp'?'MCP':'Skills'}</Button>)}</div>}{mode==='extensions'&&tab==='plugin'?<PluginLibrary/>:<><Input aria-label="搜索配置" placeholder="搜索" value={query} onChange={e=>setQuery(e.target.value)} className="mb-6 max-w-xs"/>{error&&<p role="alert" className="mb-4 text-sm text-destructive">{error}</p>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{rows.map(row=><article className="rounded-lg border bg-popover p-4" key={row.id}><div className="mb-5 flex items-center gap-3"><Icon className="size-5 shrink-0 text-muted-foreground"/><h2 className="truncate text-sm font-medium">{row.name}</h2></div><div className="mb-4 break-words text-xs text-muted-foreground">{kind==='task'?scheduleLabel(row):kind==='mcp'?row.transport.toUpperCase():'Skill'}</div>{row.lastRun&&<div className="mb-3 text-xs" title={row.lastRun.error??undefined}>{({completed:'已完成',running:'执行中',missed:'已错过',failed:'失败',stopped:'已停止',interrupted:'已中断'} as Record<string,string>)[row.lastRun.status]??row.lastRun.status}</div>}<div className="flex items-center gap-1 border-t pt-3"><Button size="sm" variant="ghost" aria-label={`${row.enabled?'停用':'启用'} ${row.name}`} onClick={()=>toggle(row.id)}>{row.enabled?'已启用':'已停用'}</Button><Button variant="ghost" size="icon" className="ml-auto size-8" aria-label={`编辑 ${row.name}`} onClick={()=>edit(row)}><Pencil className="size-3.5"/></Button><Button variant="ghost" size="icon" className="size-8" aria-label={`删除 ${row.name}`} onClick={()=>setDeleting(row)}><Trash2 className="size-3.5"/></Button></div></article>)}</div>{!rows.length&&<div className="py-12 text-center text-sm text-muted-foreground">{query?'没有匹配项':'暂无配置'}</div>}</>}</div><AlertDialog open={!!deleting} onOpenChange={v=>{if(!v)setDeleting(null)}}><AlertDialogContent aria-describedby={undefined} className="w-[calc(100%-2rem)] rounded-lg"><AlertDialogHeader><AlertDialogTitle>删除 {deleting?.name}？</AlertDialogTitle></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={()=>{if(deleting)remove(deleting.id);setDeleting(null)}}>删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>
}

